all:
	make evacuation
	make parking
	make teams

evacuation: src/evacuation.py
	@echo "python3.6 src/evacuation.py" > evacuation
	@chmod 777 evacuation

parking: src/parking.py
	@echo "python3.6 src/parking.py" > parking
	@chmod 777 parking

teams: src/teams.py
	@echo "python3.6 src/teams.py" > teams
	@chmod 777 teams