all:
	make performance
	make inspection
	make isp

performance: src/performance.py
	@echo "python3.6 src/performance.py" > performance
	@chmod 777 performance

inspection: src/inspection.py
	@echo "python3.6 src/inspection.py" > inspection
	@chmod 777 inspection

isp: src/isp.py
	@echo "python3.6 src/isp.py" > isp
	@chmod 777 isp