all:
	make launch
	make weakness
	make escape
	make avltree

launch:	src/launch.py
	@echo "python3.6 src/launch.py" > launch
	@chmod 777 launch

weakness: src/weakness.py
	@echo "python3.6 src/weakness.py" > weakness
	@chmod 777 weakness

escape: src/escape.py
	@echo "python3.6 src/escape.py" > escape
	@chmod 777 escape

avltree: src/avltree.py
	@echo "python3.6 src/avltree.py" > avltree
	@chmod 777 avltree