all:
	make akce
	make sky_links
	make holidays
	make wander
	make company
	make communication
	make distribution
	make travel

akce:	src/akce.py
	@echo "python3.6 src/akce.py" > akce
	@chmod 777 akce

sky_links: src/sky_links.py
	@echo "python3.6 src/sky_links.py" > sky_links
	@chmod 777 sky_links

holidays: src/holidays.py
	@echo "python3.6 src/holidays.py" > holidays
	@chmod 777 holidays

wander: src/wander.py
	@echo "python3.6 src/wander.py" > wander
	@chmod 777 wander

company: src/company.py
	@echo "python3.6 src/company.py" > company
	@chmod 777 company

communication: src/communication.py
	@echo "python3.6 src/communication.py" > communication
	@chmod 777 communication

distribution: src/distribution.py
	@echo "python3.6 src/distribution.py" > distribution
	@chmod 777 distribution

travel: src/travel.py
	@echo "python3.6 src/travel.py" > travel
	@chmod 777 travel